name: Portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  get: ^4.6.6
  flutter_speed_dial: ^7.0.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.6
  community_material_icon: ^5.9.55
  google_maps_flutter: ^2.5.0
  location: ^5.0.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  sliding_sheet: ^0.5.2
  iconsax: ^0.0.8
  country_icons: ^2.0.2
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  velocity_x: ^4.1.2
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cv_icon.png"

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/welcome.png
  color: "#f7f6f1"
  image_dark: assets/images/welcome_dark.png
  color_dark: "#272727"

  android_12:
    image: assets/images/welcome.png
    color: "#f7f6f1"
    image_dark: assets/images/welcome_dark.png
    color_dark: "#272727"
  web: false



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/frameworks/
     - assets/img/background/
     - animations/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700